In [128]:
import logging
import json
import numpy as np
from datetime import datetime, timedelta

In [129]:
import matlab.engine

# Start MATLAB
eng = matlab.engine.start_matlab()

In [130]:
# Add path if needed
eng.addpath(r'./matlab_code', nargout=0)

eng.eval("initialiseScenario", nargout=0)

In [131]:
np.array(eng.workspace['t'])

array(1.)

In [132]:
eng.eval("stepScenario", nargout=0)

In [133]:
tIndex = 0

In [134]:
FreqAlloc = np.array(eng.workspace['FreqAlloc'])

In [135]:
FreqAlloc[:,0]

array([ 4.,  2., 12., 14., 10.,  8., 14., 13.,  4., 15.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [127]:
FreqAlloc[:,0]

array([11.,  5., 13., 13.,  1.,  5.,  5., 15., 15., 12.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
FreqAlloc = np.array(eng.workspace['FreqAlloc'])[:,tIndex]
# Example: FreqAlloc = np.array([...])
unique_values, counts = np.unique(FreqAlloc, return_counts=True)

# Count how many values are repeated (i.e., count > 1)
num_repeated = np.sum(counts > 1)   

In [16]:
FreqAlloc

array([ 4.,  2., 12., 14., 10.,  8., 14., 13.,  4., 15.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
leo_loc = np.array(eng.workspace['LEO_LOC'])   # ✅ Correct

In [27]:
FreqAlloc = np.array(eng.workspace['FreqAlloc'])[:,0]
# Example: FreqAlloc = np.array([...])
unique_values, counts = np.unique(FreqAlloc, return_counts=True)

# Count how many values are repeated (i.e., count > 1)
num_repeated = np.sum(counts > 1)   

In [34]:
for i in range(len(unique_values)):
    print(f'unique_value: {unique_values[i]} , count: {counts[i]}')


unique_value: 1.0 , count: 1
unique_value: 2.0 , count: 2
unique_value: 3.0 , count: 1
unique_value: 4.0 , count: 2
unique_value: 5.0 , count: 1
unique_value: 6.0 , count: 2
unique_value: 7.0 , count: 3
unique_value: 8.0 , count: 2
unique_value: 9.0 , count: 2
unique_value: 10.0 , count: 1
unique_value: 12.0 , count: 2
unique_value: 15.0 , count: 1


In [28]:
print(num_repeated)

7


In [26]:
print(FreqAlloc[:,0])

[ 6.  2.  7. 15.  7.  8. 12. 12.  4.  9.  1.  2.  3.  4.  5.  6.  7.  8.
  9. 10.]


In [24]:
print(FreqAlloc.shape)

(20, 121)


In [ ]:
leo_loc.shape

In [ ]:
leo_loc[0:10,0].flatten()

In [ ]:
Serv_idxLEO = np.array(eng.workspace['Serv_idxLEO'])

In [ ]:
tidx = 0

In [ ]:
Serv_idxLEO[:10,tidx]

In [ ]:
eng.eval("resetScenario", nargout=0)
channel_list_leo = np.array(eng.workspace['ChannelListLeo'])

In [ ]:
# Store original values for comparison
before_vals = []
for i in range(10):
    sat = Serv_idxLEO[i, tidx].astype(int) - 1
    before_vals.append(channel_list_leo[i, sat, tidx])

# Now do the assignment
values = np.arange(100, 110)
for i in range(10):
    sat = Serv_idxLEO[i, tidx].astype(int) - 1
    channel_list_leo[i, sat, tidx] = values[i]

# Compare
for i in range(10):
    sat = Serv_idxLEO[i, tidx].astype(int) - 1
    print(f"User {i}: Before = {before_vals[i]}, After = {channel_list_leo[i, sat, tidx]}")


In [ ]:
channel_list_leo = np.array(eng.workspace['ChannelListLeo'])
# channel_list_leo[0,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx] = [0,1,2,3,4,5,6,7,8,9]
values = np.arange(100, 110)
for leoUserIdx in range(10):
    print("leoUserIdx:", leoUserIdx)
    print("tidx:", tidx)
    print("Serv_idxLEO[leoUserIdx, tidx]:",Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1)
    print("values[leoUserIdx]:",values[leoUserIdx])
    print("channel_list_leo[leoUserIdx, Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1, tidx]",channel_list_leo[leoUserIdx, Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1, tidx])
    channel_list_leo[leoUserIdx, Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1, tidx] = int(values[leoUserIdx])
    print("channel_list_leo[leoUserIdx, Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1, tidx]",channel_list_leo[leoUserIdx, Serv_idxLEO[leoUserIdx, tidx].astype(int) - 1, tidx])

In [ ]:
Serv_idxLEO[:10,tidx].astype(int) - 1

In [ ]:
Serv_idxLEO[:10,tidx] -1

In [ ]:
channel_list_leo[5,[582, 582,  28, 485, 534, 582, 536, 582, 584, 584],0]

In [ ]:
print(channel_list_leo[0,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[1,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[2,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[3,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[4,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[5,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[6,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[7,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[8,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[9,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[10,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[11,Serv_idxLEO[:10,tidx].astype(int) - 1,tidx])

In [ ]:
print(channel_list_leo[0,Serv_idxLEO[0,tidx].astype(int) - 1,tidx])
print(channel_list_leo[1,Serv_idxLEO[1,tidx].astype(int) - 1,tidx])
print(channel_list_leo[2,Serv_idxLEO[2,tidx].astype(int) - 1,tidx])
print(channel_list_leo[3,Serv_idxLEO[3,tidx].astype(int) - 1,tidx])
print(channel_list_leo[4,Serv_idxLEO[4,tidx].astype(int) - 1,tidx])
print(channel_list_leo[5,Serv_idxLEO[5,tidx].astype(int) - 1,tidx])
print(channel_list_leo[6,Serv_idxLEO[6,tidx].astype(int) - 1,tidx])
print(channel_list_leo[7,Serv_idxLEO[7,tidx].astype(int) - 1,tidx])
print(channel_list_leo[8,Serv_idxLEO[8,tidx].astype(int) - 1,tidx])
print(channel_list_leo[9,Serv_idxLEO[9,tidx].astype(int) - 1,tidx])
print(channel_list_leo[10,Serv_idxLEO[10,tidx].astype(int) - 1,tidx])
print(channel_list_leo[11,Serv_idxLEO[11,tidx].astype(int) - 1,tidx])

In [ ]:
eng.workspace['ChannelListLeo'] = matlab.double(channel_list_leo)

In [ ]:
eng.eval("P06_Intf_Eval", nargout=0)
FreqAlloc = np.array(eng.workspace['FreqAlloc'])

In [ ]:
FreqAlloc[:,0]

In [ ]:
SINR = np.array(eng.workspace['SINR'])
Intf = np.array(eng.workspace['Intf'])

In [ ]:
Interference_to_geo_users = Intf[10:10+ 10, 0]

In [ ]:
Interference_to_geo_users

In [ ]:
Intf[:,0]

In [ ]:
Intf[10:10+ 10, 0]

In [ ]:
Thrpt = np.array(eng.workspace['Thrpt'])

In [ ]:
Thrpt[:,0]

In [ ]:
import math
math.log2

In [ ]:
SINR[:10,0][0] / Interference_to_geo_users[0]

In [ ]:
SINR[:10,0] / Interference_to_geo_users

In [ ]:
reward = np.sum(SINR[:10,0] / Interference_to_geo_users)

In [ ]:
FreqAlloc = np.array(eng.workspace['FreqAlloc'])
LeoFreqAlloc = FreqAlloc[:10,:]
GeoFreqAlloc = FreqAlloc[10:20,:]

In [ ]:
FreqAlloc[:,0]

In [ ]:
GeoFreqAlloc[:,0]

In [ ]:
LeoFreqAlloc[:,0]

In [ ]:
np.array(eng.workspace['ChannelListLeo'])[0,582,0]

In [ ]:
np.array(eng.workspace['Serv_idxLEO'])[0,0]

In [ ]:
np.array(eng.workspace['FreqAlloc']).shape

In [ ]:
np.array(eng.workspace['FreqAlloc'])[0,0]

In [ ]:
NumLeoUser = int(eng.workspace['NumLeoUser'])

In [ ]:
NumLeoUser

In [ ]:
Serv_idxLEO = np.array(eng.workspace['Serv_idxLEO'])
# Access the variable from MATLAB workspace
channel_list_leo = eng.workspace['ChannelListLeo']

import numpy as np

# Convert MATLAB array to NumPy array
channel_list_leo_np = np.array(channel_list_leo)

channel_list_leo_np[0, 0, 0] = 200
channel_list_leo_np[0, int(Serv_idxLEO[0,0])-1, 0] = 2
eng.workspace['ChannelListLeo'] = matlab.double(channel_list_leo_np)


In [ ]:
eng.eval("resetScenario", nargout=0)

In [ ]:
np.array(eng.workspace['ChannelListLeo'])

In [ ]:
eng.eval("stepScenario", nargout=0)

In [ ]:
np.array(eng.workspace['ChannelListLeo'])[0,582,0]

In [ ]:
np.array(eng.workspace['Serv_idxLEO'])[0,0]

In [ ]:
ts = eng.workspace['ts']

In [ ]:
type(ts)

In [ ]:
ts_str = eng.eval("cellstr(datestr(ts, 'yyyy-mm-ddTHH:MM:SS'))", nargout=1)
python_datetimes = [datetime.fromisoformat(s) for s in ts_str]


In [ ]:
def get_matlab_ts():
    """
    Get the MATLAB timestamp as a list of strings.
    """
    ts_str = eng.eval("cellstr(datestr(ts, 'yyyy-mm-ddTHH:MM:SS'))", nargout=1)
    python_datetimes = [datetime.fromisoformat(s) for s in ts_str]
    return python_datetimes

In [ ]:
get_matlab_ts()

In [ ]:
timelength = eng.eval("length(ts)", nargout=1)

In [ ]:
timelength

In [ ]:
SINR = np.array(eng.workspace['SINR'])

In [ ]:
SINR.shape

In [ ]:
SINR[:,0]

In [ ]:
SINR[:,0].shape

In [ ]:
# Access the variable from MATLAB workspace
channel_list_leo = eng.workspace['ChannelListLeo']

import numpy as np

# Convert MATLAB array to NumPy array
channel_list_leo_np = np.array(channel_list_leo)


In [ ]:
channel_list_leo_np[0, 0, :]

In [ ]:
Serv_idxLEO = np.array(eng.workspace['Serv_idxLEO'])

In [ ]:
Serv_idxLEO[0:,0].shape

In [ ]:
Serv_idxLEO[0,0]

In [ ]:
np.array(eng.workspace['FreqAlloc']).shape